-- Progression tables
create table scope (
 name varchar (32) primary key
);
create table progression (
  id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
  client_id int not null,
  date date not null,
  foreign key (client_id) references client(id) ON DELETE CASCADE ON UPDATE CASCADE,
  primary key (id)
);
create table progression_value (
   id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
   progression_id int not null,
   scope_name varchar (32) not null,
   value decimal (5, 2),
   foreign key (progression_id) references progression(id) ON DELETE CASCADE ON UPDATE CASCADE,
   foreign key (scope_name) references scope(name) ON DELETE CASCADE ON UPDATE CASCADE,
   primary key (id)
);
-- Data
insert into capability values ('progression_progressions', '/progression/progressions/**');
insert into role_capability values ('entrenador', 'progression_progressions');
insert into role_write_capability values ('entrenador', 'progression_progressions');

insert into scope values ('WEIGHT');
insert into scope values ('FAT_PERCENTAGE');
insert into scope values ('ABDOMINAL_FAT');
insert into scope values ('MUSCLE_WEIGHT');
insert into scope values ('METABOLIC_AGE');
insert into scope values ('BASAL_METABOLISM');



