create table event (
 id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
 client_id int not null,
 title varchar(255) not null,
 init timestamp not null,
 end timestamp not null,
 foreign key (client_id) references client(id) ON DELETE CASCADE ON UPDATE CASCADE,
 primary key (id)
);
-- Data
insert into capability values ('schedule_schedule', '/schedule/schedule/**');
insert into role_capability values ('entrenador', 'schedule_schedule');
insert into role_write_capability values ('entrenador', 'schedule_schedule');




